import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
// import "./globals.css";
import Sidebar from "../../components/Sidebar";
import FilterProvider from "../../components/FilterProvider";
import { ModalProvider } from "../../components/ModalProvider";
import ModalController from "../../components/ModalController";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} font-sans antialiased bg-gradient-to-br from-[#ffa141]/10 via-[#7daab1]/10 to-[#257282]/10`}
      >
        {/* ModalProvider lives at the top so any child (like pages/components) can open it */}
        <ModalProvider>
          {/* ModalController is a client component that consumes the ModalProvider hook */}
          <ModalController />

          <div className="relative min-h-screen">
            <FilterProvider>
              <Sidebar />

              <div
                className="
                  transition-all duration-300
                  md:pl-24
                  lg:pl-96
                "
              >
                <main
                  className="
                    min-h-screen w-full
                    w-[94%]
                    md:max-w-[80vw]
                    mx-auto
                    px-6 py-12
                    lg:px-10 xl:px-12
                  "
                >
                  <div className="block md:hidden">searchbar and filter</div>

                  {children}
                </main>
              </div>
            </FilterProvider>
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}